version: '3.4'
  
networks:
  web:
    external:
      name: web
services:
  go-api:
    labels:
      - 'traefik.backend=go-api'
      - 'traefik.port=8040'
      - 'traefik.frontend.rule=Host:api.lifereferencemanual.net'
    networks:
      web:
    image: wayimp/go-api
    ports:
      - 8040:8040
      - 27021:27017