version: '3.4'
  
networks:
  web:
    external:
      name: web
services:
  go-api:
    env_file:
      - .env
    labels:
      - 'traefik.backend=go-api'
      - 'traefik.port=8041'
      - 'traefik.frontend.rule=Host:api.gothereforeministries.org'
    networks:
      web:
    image: wayimp/go-api
    ports:
      - 8041:8041
      - 27021:27017